# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.

name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Project_Name: .\Blackjack\BlackJack.v3\BlackJack.v3.csproj
      Test_Project_Path: .\Blackjack\CoreGameTesting\CoreGameTesting.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path

    - name: Build Game
      run: dotnet build $env:Project_Name -c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
